export {default as Tags} from './Tags';
export {default as InpageCategory} from './InpageCategory';
export {default as Info} from './Info';
export {default as Propose} from './Propose';
export {default as CommentForm} from './CommentForm';
export * from './PageSmList';
export * from './CommentList';
export * from './HorizonList';
export * from './TopPage';
export * from './DupList';