<?php

$resposne = [ // app/Services/StripeService.php:59
  "id" => "cs_test_a1RWfIVl3rMj2k8AYFdnhj4qnVwsEBN4ff419DrVd2P6O2z3KaWo9FKdnN"
  "object" => "checkout.session"
  "adaptive_pricing" => array:1 [▶]
  "after_expiration" => null
  "allow_promotion_codes" => null
  "amount_subtotal" => 600
  "amount_total" => 600
  "automatic_tax" => array:4 [▶]
  "billing_address_collection" => null
  "branding_settings" => array:7 [▶]
  "cancel_url" => null
  "client_reference_id" => null
  "client_secret" => null
  "collected_information" => null
  "consent" => null
  "consent_collection" => null
  "created" => 1766310037
  "currency" => "usd"
  "currency_conversion" => null
  "custom_fields" => []
  "custom_text" => array:4 [▶]
  "customer" => null
  "customer_account" => null
  "customer_creation" => "if_required"
  "customer_details" => null
  "customer_email" => null
  "discounts" => []
  "expires_at" => 1766396437
  "invoice" => null
  "invoice_creation" => array:2 [▶]
  "livemode" => false
  "locale" => null
  "metadata" => []
  "mode" => "payment"
  "origin_context" => null
  "payment_intent" => null
  "payment_link" => null
  "payment_method_collection" => "if_required"
  "payment_method_configuration_details" => array:2 [▶]
  "payment_method_options" => array:1 [▶]
  "payment_method_types" => array:6 [▶]
  "payment_status" => "unpaid"
  "permissions" => null
  "phone_number_collection" => array:1 [▶]
  "recovered_from" => null
  "saved_payment_method_options" => null
  "setup_intent" => null
  "shipping_address_collection" => null
  "shipping_cost" => null
  "shipping_options" => []
  "status" => "open"
  "submit_type" => null
  "subscription" => null
  "success_url" => "http://acar11x.dev/"
  "total_details" => array:3 [▶]
  "ui_mode" => "hosted"
  "url" => "https://checkout.stripe.com/c/pay/cs_test_a1RWfIVl3rMj2k8AYFdnhj4qnVwsEBN4ff419DrVd2P6O2z3KaWo9FKdnN#fidnandhYHdWcXxpYCc%2FJ2FgY2RwaXEnKSdkdWxOYHwnPyd1blpxYHZxWjA0VmJNTnNARl9pT0dqN1I9V0dhZ3RhZElAdFFoSWFcZnxoUWtUZn00XTxVVFR2UV1nRGlQUTJmMTRzbjVxbURTcnNodFVkNmBMUkdvUkFxVGlfX1BzbH1nNTVhUE9qaGJzbCcpJ2N3amhWYHdzYHcnP3F3cGApJ2dkZm5id2pwa2FGamlqdyc%2FJyZjY2NjY2MnKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSdga2RnaWBVaWRmYG1qaWFgd3YnP3F3cGB4JSUl ◀"
  "wallet_options" => null
]